build: false

environment:
  matrix:
    - PYTHON: C:\Python36-x64

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - python -m pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -e .[dev,docs]

test_script:
  - mkdir test
  - echo 1 > test\sample-1.in
  - echo 1 > test\sample-2.in
  - echo 1 > test\sample-3.in
  - echo 1 > test\sample-4.in
  - echo 1 > test\sample-5.in
  - echo 1 > test\sample-6.in
  - echo 1 > test\sample-7.in
  - echo 1 > test\sample-8.in
  - echo 1 > test\sample-9.in
  # - echo 1 > test\sample-10.in
  - python -m onlinejudge._implementation.main generate-output --jobs 8 -c "echo 1"
  - python -m onlinejudge._implementation.main generate-output --jobs 8 -c "echo 1"
  - python -m onlinejudge._implementation.main generate-output --jobs 8 -c "echo 1"
  - python -m onlinejudge._implementation.main generate-output --jobs 8 -c "echo 1"
  - python -m onlinejudge._implementation.main generate-output --jobs 8 -c "echo 1"
  - python -m onlinejudge._implementation.main generate-output --jobs 8 -c "echo 1"
  - python -m onlinejudge._implementation.main generate-output --jobs 8 -c "echo 1"
  - python -m onlinejudge._implementation.main generate-output --jobs 8 -c "echo 1"
  - python -m onlinejudge._implementation.main generate-output --jobs 8 -c "echo 1"
  - python -m onlinejudge._implementation.main generate-output --jobs 8 -c "echo 1"

artifacts:
  - path: dist\oj.exe
    name: oj_exe

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: z5/wB9Or6BhMxAJ2vh31xOtI2REiETaYMykjvsp1D9mqruhzCtlyeiGHPUxAEI0T
  artifact: oj_exe
  force_update: true
  draft: false
  on:
    appveyor_repo_tag: true
    branch: master
    PYTHON_VERSION: 3.6
